#https://developers.google.com/appengine/docs/python/config/appconfig
application: hackillinois-dev
module: default
version: 2-0-2
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10m"
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /assets
  static_dir: assets

#https://developers.google.com/appengine/articles/python/recording_exceptions_with_ereporter
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
  
- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

#https://developers.google.com/appengine/docs/python/tools/appstats?csw=1
builtins:
- appstats: on
- remote_api: on
- deferred: on
